export const BOOKS = [
  {
    id: "loops",
    title: "Loops",
    desc: "Repeat. Iterate. Echo. The first spell every programmer learns.",
    chapter: "Ch. 1",
    pages: 24,
    color: "#f5b04c",
    edge: "#b07020",
    glow: "#ffd685",
    spine: "loops",
    height: 110,
    width: 28,
    tilt: -3,
  },
  {
    id: "functions",
    title: "Functions",
    desc: "Wrap intent into a name and call it forever.",
    chapter: "Ch. 2",
    pages: 31,
    color: "#5b9b94",
    edge: "#2d6b62",
    glow: "#7fc4bd",
    spine: "lambda",
    height: 132,
    width: 26,
    tilt: 2,
  },
  {
    id: "algorithms",
    title: "Algorithms",
    desc: "Recipes for thinking. Patterns that move mountains.",
    chapter: "Ch. 3",
    pages: 48,
    color: "#e85a6e",
    edge: "#a02a3a",
    glow: "#ff8a9a",
    spine: "maze",
    height: 144,
    width: 32,
    tilt: -1,
  },
  {
    id: "datastructures",
    title: "Data Structures",
    desc: "How memory remembers shape. Trees, graphs, lists, dreams.",
    chapter: "Ch. 4",
    pages: 42,
    color: "#8b6db0",
    edge: "#5a3f80",
    glow: "#b594d9",
    spine: "tree",
    height: 138,
    width: 30,
    tilt: 4,
  },
  {
    id: "networking",
    title: "Networking",
    desc: "Voices across the wires. Whispers between machines.",
    chapter: "Ch. 5",
    pages: 36,
    color: "#7faedb",
    edge: "#4a76b0",
    glow: "#cce7ff",
    spine: "nodes",
    height: 120,
    width: 28,
    tilt: -2,
  },
  {
    id: "memory",
    title: "Memory",
    desc: "A grid of small rooms holding everything you know.",
    chapter: "Ch. 6",
    pages: 28,
    color: "#c4905e",
    edge: "#7a4a2a",
    glow: "#d49a5a",
    spine: "grid",
    height: 128,
    width: 30,
    tilt: 1,
  },
  {
    id: "security",
    title: "Security",
    desc: "Locks, keys, and the quiet art of saying no.",
    chapter: "Ch. 7",
    pages: 33,
    color: "#3a6b3f",
    edge: "#1f3d2a",
    glow: "#6ba85a",
    spine: "lock",
    height: 116,
    width: 26,
    tilt: -3,
  },
] as const;

export type BookData = (typeof BOOKS)[number];
